<?php

/**
 * @file
 * Functions to support theming in the custom_theme theme.
 */

use Drupal\Core\Render\Element;
use Drupal\block_content\Entity\BlockContent;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme_suggestions_views_view_alter().
 */
function custom_theme_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $suggestions[] = sprintf('views_view__%s__%s', $variables['view']->id(), $variables['view']->current_display);
}